//! Vulkan Video session and decode smoke-test snapshot data.

use serde::Serialize;

use super::codec::NativeVulkanVideoSessionCodec;
use super::codec_snapshots::NativeVulkanVideoBitstreamExtractSnapshot;

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoSessionSmokeSnapshot {
    pub result: &'static str,
    pub requested_codec: NativeVulkanVideoSessionCodec,
    pub requested_extent: (u32, u32),
    pub selected_physical_device_index: usize,
    pub selected_physical_device_name: String,
    pub selected_physical_device_type: &'static str,
    pub vendor_id: u32,
    pub device_id: u32,
    pub api_version: String,
    pub driver_version: u32,
    pub selected_queue_family_index: u32,
    pub selected_queue_count: u32,
    pub selected_queue_flags: Vec<&'static str>,
    pub selected_queue_video_codec_operations: Vec<String>,
    pub selected_queue_query_result_status_support: bool,
    pub enabled_device_extensions: Vec<&'static str>,
    pub video_maintenance1_enabled: bool,
    pub decode_query_status_enabled: bool,
    pub video_codec_operation: Vec<String>,
    pub profile: &'static str,
    pub picture_format: &'static str,
    pub reference_picture_format: &'static str,
    pub target_picture_dpb_supported: bool,
    pub target_picture_output_supported: bool,
    pub target_picture_sampled_output_supported: bool,
    pub nv12_dpb_supported: bool,
    pub nv12_output_supported: bool,
    pub nv12_sampled_output_supported: bool,
    pub capability_flags: Vec<&'static str>,
    pub decode_capability_flags: Vec<&'static str>,
    pub min_bitstream_buffer_offset_alignment: u64,
    pub min_bitstream_buffer_size_alignment: u64,
    pub picture_access_granularity: (u32, u32),
    pub min_coded_extent: (u32, u32),
    pub max_coded_extent: (u32, u32),
    pub requested_extent_supported: bool,
    pub driver_max_dpb_slots: u32,
    pub driver_max_active_reference_pictures: u32,
    pub session_max_dpb_slots: u32,
    pub session_max_active_reference_pictures: u32,
    pub codec_max_level: Option<String>,
    pub std_header_version_name: String,
    pub std_header_version_spec_version: u32,
    pub memory_requirement_count: usize,
    pub total_bound_memory_bytes: u64,
    pub memory_requirements: Vec<NativeVulkanVideoSessionMemoryRequirementSnapshot>,
    pub video_images_requested: bool,
    pub video_image_count: usize,
    pub total_video_image_memory_bytes: u64,
    pub video_images: Vec<NativeVulkanVideoSessionResourceImageSnapshot>,
    pub bitstream_buffer_requested: bool,
    pub bitstream_buffer: Option<NativeVulkanVideoSessionBitstreamBufferSnapshot>,
    pub bitstream_extract_requested: bool,
    pub bitstream_extract: Option<NativeVulkanVideoBitstreamExtractSnapshot>,
    pub session_parameters_requested: bool,
    pub session_parameters_created: bool,
    pub session_parameters_error: Option<String>,
    pub session_parameters: Option<NativeVulkanVideoSessionParametersSnapshot>,
    pub first_frame_decode_requested: bool,
    pub first_frame_decode: Option<NativeVulkanVideoFirstFrameDecodeSnapshot>,
    pub h264_idr_prefix_decode_requested: bool,
    pub h264_idr_prefix_decode: Option<NativeVulkanH264IdrPrefixDecodeSnapshot>,
    pub h264_ready_prefix_decode_requested: bool,
    pub h264_ready_prefix_decode: Option<NativeVulkanH264ReadyPrefixDecodeSnapshot>,
    pub h265_ready_prefix_decode_requested: bool,
    pub h265_ready_prefix_decode: Option<NativeVulkanH265ReadyPrefixDecodeSnapshot>,
    pub session_created: bool,
    pub session_memory_bound: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoSessionMemoryRequirementSnapshot {
    pub memory_bind_index: u32,
    pub size: u64,
    pub alignment: u64,
    pub memory_type_bits: u32,
    pub selected_memory_type_index: u32,
    pub selected_memory_property_flags: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoSessionResourceImageSnapshot {
    pub role: &'static str,
    pub format: &'static str,
    pub image_type: &'static str,
    pub image_tiling: &'static str,
    pub image_usage_flags: Vec<&'static str>,
    pub image_create_flags: Vec<&'static str>,
    pub extent: (u32, u32, u32),
    pub array_layers: u32,
    pub image_view_type: &'static str,
    pub image_view_created: bool,
    pub memory_size: u64,
    pub memory_alignment: u64,
    pub memory_type_bits: u32,
    pub selected_memory_type_index: u32,
    pub selected_memory_property_flags: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoSessionBitstreamBufferSnapshot {
    pub requested_size: u64,
    pub size: u64,
    pub min_size_alignment: u64,
    pub usage_flags: Vec<&'static str>,
    pub memory_size: u64,
    pub memory_alignment: u64,
    pub memory_type_bits: u32,
    pub selected_memory_type_index: u32,
    pub selected_memory_property_flags: Vec<&'static str>,
    pub mapped_write_bytes: u64,
    pub mapped_write_source: &'static str,
    pub mapped_write_hash: Option<u64>,
    pub host_visible: bool,
    pub host_coherent: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoSessionParametersSnapshot {
    pub codec: &'static str,
    pub source: &'static str,
    pub max_std_vps_count: u32,
    pub max_std_sps_count: u32,
    pub max_std_pps_count: u32,
    pub std_vps_count: u32,
    pub std_sps_count: u32,
    pub std_pps_count: u32,
    pub vps_id: u8,
    pub sps_id: u32,
    pub pps_id: u32,
    pub profile_idc: u8,
    pub level_idc: u8,
    pub width: u32,
    pub height: u32,
    pub created: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoFirstFrameDecodeSnapshot {
    pub codec: &'static str,
    pub command_pool_created: bool,
    pub command_buffer_allocated: bool,
    pub command_buffer_recorded: bool,
    pub submitted: bool,
    pub completed: bool,
    pub queue_family_index: u32,
    pub source_layout: &'static str,
    pub decode_layout: &'static str,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub dst_base_array_layer: u32,
    pub setup_slot_index: i32,
    pub begin_reference_slot_count: u32,
    pub decode_reference_slot_count: u32,
    pub reset_control_recorded: bool,
    pub slice_segment_count: u32,
    pub slice_segment_offsets: Vec<u32>,
    pub nal_type: u8,
    pub nal_type_label: &'static str,
    pub first_slice_segment_in_pic_flag: bool,
    pub slice_type: u32,
    pub pps_id: u32,
    pub sps_video_parameter_set_id: u8,
    pub pps_seq_parameter_set_id: u8,
    pub pps_pic_parameter_set_id: u8,
    pub pic_order_cnt_val: i32,
    pub idr: bool,
    pub irap: bool,
    pub output_readback: Option<NativeVulkanVideoDecodeOutputReadbackSnapshot>,
    pub output_sampling: Option<NativeVulkanVideoDecodeOutputSamplingSnapshot>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265ReadyPrefixDecodeSnapshot {
    pub codec: &'static str,
    pub requested_frame_count: u32,
    pub decoded_frame_count: u32,
    pub completed: bool,
    pub submitted: bool,
    pub queue_family_index: u32,
    pub command_pool_created: bool,
    pub command_buffer_allocated: bool,
    pub command_buffer_recorded: bool,
    pub begin_reference_slot_count: u32,
    pub reset_control_recorded: bool,
    pub reset_control_count: u32,
    pub decode_query_status_enabled: bool,
    pub decode_query_count: u32,
    pub src_buffer_total_bytes: u64,
    pub readback_access_unit_index: u32,
    pub readback_base_array_layer: u32,
    pub frames: Vec<NativeVulkanH265DecodedFrameSnapshot>,
    pub output_readback: Option<NativeVulkanVideoDecodeOutputReadbackSnapshot>,
    pub output_sampling: Option<NativeVulkanVideoDecodeOutputSamplingSnapshot>,
    pub output_sampling_sequence: Vec<NativeVulkanH265ReadyPrefixSampledFrameSnapshot>,
    pub output_sampling_sequence_timing:
        Option<NativeVulkanH265ReadyPrefixSamplingSequenceTimingSnapshot>,
    pub output_render_sequence: Vec<NativeVulkanH265ReadyPrefixRenderedFrameSnapshot>,
    pub output_render_sequence_timing:
        Option<NativeVulkanH265ReadyPrefixRenderSequenceTimingSnapshot>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH264IdrPrefixDecodeSnapshot {
    pub codec: &'static str,
    pub requested_frame_count: u32,
    pub decoded_frame_count: u32,
    pub completed: bool,
    pub submitted: bool,
    pub queue_family_index: u32,
    pub command_pool_created: bool,
    pub command_buffer_allocated: bool,
    pub command_buffer_recorded: bool,
    pub begin_reference_slot_count: u32,
    pub reset_control_recorded: bool,
    pub reset_control_count: u32,
    pub src_buffer_total_bytes: u64,
    pub readback_access_unit_index: u32,
    pub readback_base_array_layer: u32,
    pub frames: Vec<NativeVulkanH264DecodedFrameSnapshot>,
    pub output_readback: Option<NativeVulkanVideoDecodeOutputReadbackSnapshot>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH264ReadyPrefixDecodeSnapshot {
    pub codec: &'static str,
    pub requested_frame_count: u32,
    pub decoded_frame_count: u32,
    pub completed: bool,
    pub submitted: bool,
    pub queue_family_index: u32,
    pub command_pool_created: bool,
    pub command_buffer_allocated: bool,
    pub command_buffer_recorded: bool,
    pub begin_reference_slot_count: u32,
    pub reset_control_recorded: bool,
    pub reset_control_count: u32,
    pub src_buffer_total_bytes: u64,
    pub readback_access_unit_index: u32,
    pub readback_base_array_layer: u32,
    pub frames: Vec<NativeVulkanH264DecodedFrameSnapshot>,
    pub output_readback: Option<NativeVulkanVideoDecodeOutputReadbackSnapshot>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH264DecodedFrameSnapshot {
    pub access_unit_index: u32,
    pub pts_ms: Option<u64>,
    pub nal_type: u8,
    pub nal_type_label: &'static str,
    pub nal_ref_idc: u8,
    pub slice_type: u32,
    pub field_pic_flag: bool,
    pub bottom_field_flag: bool,
    pub frame_num: u16,
    pub idr_pic_id: u16,
    pub pic_order_cnt_val: i32,
    pub pic_order_cnt: [i32; 2],
    pub idr: bool,
    pub irap: bool,
    pub used_for_long_term_reference: bool,
    pub long_term_frame_idx: Option<u16>,
    pub reset_before_decode: bool,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub dst_base_array_layer: u32,
    pub setup_slot_index: i32,
    pub decode_reference_slot_count: u32,
    pub references: Vec<NativeVulkanH264DecodedFrameReferenceSnapshot>,
    pub slice_segment_count: u32,
    pub slice_segment_offsets: Vec<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH264DecodedFrameReferenceSnapshot {
    pub reference_slot_index: u32,
    pub dpb_slot: u32,
    pub source_access_unit_index: u32,
    pub frame_num: u16,
    pub field_pic_flag: bool,
    pub bottom_field_flag: bool,
    pub used_for_long_term_reference: bool,
    pub long_term_frame_idx: Option<u16>,
    pub long_term_pic_num: Option<u16>,
    pub non_existing: bool,
    pub pic_order_cnt_val: i32,
    pub pic_order_cnt: [i32; 2],
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265ReadyPrefixSampledFrameSnapshot {
    pub access_unit_index: u32,
    pub pts_ms: Option<u64>,
    pub pts_delta_ms: Option<u64>,
    pub source_base_array_layer: u32,
    pub readback_y_hash: u64,
    pub readback_uv_hash: u64,
    pub readback_y_unique_values: u32,
    pub readback_uv_unique_values: u32,
    pub rgba_hash: u64,
    pub rgba_unique_values: u32,
    pub rgba_nonzero_bytes: u64,
    pub decode_submit_wait_elapsed_us: u64,
    pub readback_elapsed_us: u64,
    pub sampling_elapsed_us: u64,
    pub frame_elapsed_us: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265ReadyPrefixSamplingSequenceTimingSnapshot {
    pub frame_count: u32,
    pub total_elapsed_us: u64,
    pub average_frame_elapsed_us: u64,
    pub max_frame_elapsed_us: u64,
    pub max_decode_submit_wait_elapsed_us: u64,
    pub max_readback_elapsed_us: u64,
    pub max_sampling_elapsed_us: u64,
    pub pts_delta_min_ms: Option<u64>,
    pub pts_delta_max_ms: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265ReadyPrefixRenderedFrameSnapshot {
    pub access_unit_index: u32,
    pub pts_ms: Option<u64>,
    pub pts_delta_ms: Option<u64>,
    pub source_base_array_layer: u32,
    pub render_elapsed_us: u64,
    pub target_layout: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265ReadyPrefixRenderSequenceTimingSnapshot {
    pub frame_count: u32,
    pub average_render_elapsed_us: u64,
    pub max_render_elapsed_us: u64,
    pub pts_delta_min_ms: Option<u64>,
    pub pts_delta_max_ms: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265DecodedFrameSnapshot {
    pub access_unit_index: u32,
    pub pts_ms: Option<u64>,
    pub nal_type: u8,
    pub nal_type_label: &'static str,
    pub slice_type: u32,
    pub pic_order_cnt_val: i32,
    pub idr: bool,
    pub irap: bool,
    pub short_term_ref_pic_set_sps_flag: bool,
    pub num_delta_pocs_of_ref_rps_idx: u8,
    pub num_bits_for_st_ref_pic_set_in_slice: u16,
    pub reset_before_decode: bool,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub dst_base_array_layer: u32,
    pub setup_slot_index: i32,
    pub decode_reference_slot_count: u32,
    pub decode_query_status_raw: Option<i32>,
    pub decode_query_status: Option<&'static str>,
    pub references: Vec<NativeVulkanH265DecodedFrameReferenceSnapshot>,
    pub slice_segment_count: u32,
    pub slice_segment_offsets: Vec<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanH265DecodedFrameReferenceSnapshot {
    pub reference_slot_index: u32,
    pub dpb_slot: u32,
    pub source_access_unit_index: u32,
    pub poc: i32,
    pub used_for_long_term_reference: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoDecodeOutputReadbackSnapshot {
    pub format: &'static str,
    pub buffer_created: bool,
    pub copied: bool,
    pub host_visible: bool,
    pub host_coherent: bool,
    pub host_cached: bool,
    pub memory_size: u64,
    pub total_bytes: u64,
    pub y_plane_bytes: u64,
    pub uv_plane_bytes: u64,
    pub y_plane_hash: u64,
    pub uv_plane_hash: u64,
    pub combined_hash: u64,
    pub y_plane_nonzero_bytes: u64,
    pub uv_plane_nonzero_bytes: u64,
    pub y_plane_min: u8,
    pub y_plane_max: u8,
    pub uv_plane_min: u8,
    pub uv_plane_max: u8,
    pub y_plane_unique_values: u32,
    pub uv_plane_unique_values: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanVideoDecodeOutputSamplingSnapshot {
    pub source_format: &'static str,
    pub target_format: &'static str,
    pub source_layout: &'static str,
    pub shader_layout: &'static str,
    pub source_base_array_layer: u32,
    pub render_extent: (u32, u32),
    pub y_plane_view_created: bool,
    pub uv_plane_view_created: bool,
    pub color_image_created: bool,
    pub color_image_view_created: bool,
    pub renderer_created: bool,
    pub command_buffer_recorded: bool,
    pub rendered: bool,
    pub copied: bool,
    pub host_visible: bool,
    pub host_coherent: bool,
    pub host_cached: bool,
    pub color_image_memory_size: u64,
    pub readback_memory_size: u64,
    pub total_bytes: u64,
    pub rgba_hash: u64,
    pub rgba_nonzero_bytes: u64,
    pub rgba_min: u8,
    pub rgba_max: u8,
    pub rgba_unique_values: u32,
}
