use std::path::PathBuf;

use serde::Serialize;

use crate::core::FitMode;

use super::demux::NativeVulkanStreamingPacketQueueRuntimeSnapshot;
use super::direct_runtime::{NativeVulkanDirectPresentTimedFrame, NativeVulkanDirectPresentTiming};
use super::{NativeVulkanAudioClockRuntimeSnapshot, NativeVulkanVideoSessionCodec};

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanDirectH265FirstFrameDecodeSnapshot {
    pub completed: bool,
    pub queue_family_index: u32,
    pub source_layout: &'static str,
    pub decoded_layout: &'static str,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub dst_base_array_layer: u32,
    pub setup_slot_index: i32,
    pub begin_reference_slot_count: u32,
    pub decode_reference_slot_count: u32,
    pub reset_control_recorded: bool,
    pub slice_segment_count: u32,
    pub slice_segment_offsets: Vec<u32>,
    pub nal_type: u8,
    pub nal_type_label: &'static str,
    pub first_slice_segment_in_pic_flag: bool,
    pub slice_type: u32,
    pub pps_id: u32,
    pub pic_order_cnt_val: i32,
    pub idr: bool,
    pub irap: bool,
    pub decode_elapsed_us: u64,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct NativeVulkanDirectH265FirstFrameRuntimeSnapshot {
    pub runtime_elapsed_ms: u64,
    pub frames_rendered: u64,
    pub average_render_fps: f64,
    pub configured: bool,
    pub source: PathBuf,
    pub source_extent: (u32, u32),
    pub fit: FitMode,
    pub target_max_fps: Option<u32>,
    pub wayland_surface_logical_size: (u32, u32),
    pub wayland_surface_buffer_size: (u32, u32),
    pub selected_physical_device_name: String,
    pub selected_physical_device_type: &'static str,
    pub present_queue_family_index: u32,
    pub present_queue_flags: Vec<&'static str>,
    pub video_decode_queue_family_index: u32,
    pub video_decode_queue_flags: Vec<&'static str>,
    pub video_decode_queue_codec_operations: Vec<String>,
    pub cross_queue_sync_strategy: &'static str,
    pub swapchain_extent: (u32, u32),
    pub swapchain_image_count: usize,
    pub swapchain_format: String,
    pub present_mode: &'static str,
    pub pacing_strategy: &'static str,
    pub video_resource_memory_bytes: u64,
    pub session_memory_bytes: u64,
    pub bitstream_buffer_bytes: u64,
    pub decode: NativeVulkanDirectH265FirstFrameDecodeSnapshot,
    pub last_render_error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct NativeVulkanDirectH265ReadyPrefixRuntimeSnapshot {
    pub runtime_elapsed_ms: u64,
    pub requested_codec: NativeVulkanVideoSessionCodec,
    pub picture_format: &'static str,
    pub requested_frame_count: u32,
    pub ready_prefix_frame_count: u32,
    pub requested_playback_frame_count: u32,
    pub decoded_frame_count: u32,
    pub presented_frame_count: u32,
    pub decoded_frame_zero_copy_scope: &'static str,
    pub decoded_frame_zero_copy_status: &'static str,
    pub h265_present_frame_preroll_count: u32,
    pub playback_loop_count: u32,
    pub loop_boundary_reset_count: u32,
    pub frame_sleep_count: u32,
    pub missed_frame_pacing_count: u32,
    pub total_frame_sleep_us: u64,
    pub max_frame_pacing_late_us: u64,
    pub average_present_fps: f64,
    pub average_present_result_fps: f64,
    pub average_present_result_drop_first_fps: f64,
    pub average_present_result_drop_first_60_fps: f64,
    pub present_result_first_interval_us: u64,
    pub present_result_max_interval_us: u64,
    pub present_result_max_interval_after_warmup_us: u64,
    pub present_result_over_budget_count: u32,
    pub present_result_over_budget_after_warmup_count: u32,
    pub present_result_missed_vblank_threshold_us: u64,
    pub present_result_missed_vblank_count: u32,
    pub present_result_missed_vblank_after_warmup_count: u32,
    pub configured: bool,
    pub source: PathBuf,
    pub source_extent: (u32, u32),
    pub fit: FitMode,
    pub target_max_fps: Option<u32>,
    pub wayland_surface_logical_size: (u32, u32),
    pub wayland_surface_buffer_size: (u32, u32),
    pub selected_physical_device_name: String,
    pub selected_physical_device_type: &'static str,
    pub present_queue_family_index: u32,
    pub present_queue_flags: Vec<&'static str>,
    pub video_decode_queue_family_index: u32,
    pub video_decode_queue_flags: Vec<&'static str>,
    pub video_decode_queue_codec_operations: Vec<String>,
    pub cross_queue_sync_strategy: &'static str,
    pub driver_max_dpb_slots: u32,
    pub stream_sps_dpb_slots: u32,
    pub stream_dpb_slots: u32,
    pub stream_max_active_reference_pictures: u32,
    pub session_max_dpb_slots: u32,
    pub session_max_active_reference_pictures: u32,
    pub swapchain_extent: (u32, u32),
    pub swapchain_image_count: usize,
    pub swapchain_format: String,
    pub present_mode: &'static str,
    pub pacing_strategy: &'static str,
    pub video_resource_memory_bytes: u64,
    pub session_memory_bytes: u64,
    pub bitstream_buffer_bytes: u64,
    pub bitstream_buffer_strategy: &'static str,
    pub bitstream_buffer_slot_count: u32,
    pub bitstream_buffer_slot_bytes: u64,
    pub bitstream_ring_capacity_bytes: u64,
    pub bitstream_ring_min_offset_alignment: u64,
    pub bitstream_ring_min_size_alignment: u64,
    pub bitstream_ring_wrap_count: u32,
    pub bitstream_window_payload_bytes: u64,
    pub bitstream_upload_count: u32,
    pub bitstream_uploaded_bytes: u64,
    pub h265_input_mode: &'static str,
    pub h265_demux_queue: NativeVulkanStreamingPacketQueueRuntimeSnapshot,
    pub h265_display_handoff_strategy: &'static str,
    pub h265_display_ring_memory_bytes: u64,
    pub h265_display_copy_count: u32,
    pub h265_displayed_direct_dpb_count: u32,
    pub h265_present_queue_count: u32,
    pub h265_async_present_depth: u32,
    pub h265_present_result_wait_count: u32,
    pub h265_present_result_wait_elapsed_us: u64,
    pub h265_present_result_wait_max_us: u64,
    pub h265_acquire_not_ready_count: u32,
    pub h265_packet_queue_capacity: u32,
    pub h265_packet_queue_pulled_count: u32,
    pub h265_packet_queue_eos_count: u32,
    pub h265_packet_queue_loop_count: u32,
    pub h265_packet_queue_loop_skip_access_units: u32,
    pub h265_packet_queue_loop_skipped_access_units: u32,
    pub h265_packet_queue_bootstrap_discarded_access_units: u32,
    pub h265_packet_queue_max_payload_bytes: u64,
    pub h265_packet_queue_retained_payload_bytes: u64,
    pub pts_delta_min_ms: Option<u64>,
    pub pts_delta_max_ms: Option<u64>,
    pub pts_delta_expected_min_ms: Option<u64>,
    pub pts_delta_expected_max_ms: Option<u64>,
    pub pts_delta_in_expected_range: Option<bool>,
    pub audio_clock_probe: Option<NativeVulkanAudioClockRuntimeSnapshot>,
    pub frames: Vec<NativeVulkanDirectH265ReadyPrefixFrameSnapshot>,
    pub last_render_error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanDirectH265ReadyPrefixFrameSnapshot {
    pub playback_frame_index: u32,
    pub playback_loop_index: u32,
    pub ready_prefix_frame_index: u32,
    pub loop_boundary_reset: bool,
    pub access_unit_index: u32,
    pub pts_ms: Option<u64>,
    pub pts_delta_ms: Option<u64>,
    pub nal_type: u8,
    pub nal_type_label: &'static str,
    pub slice_type: u32,
    pub pic_order_cnt_val: i32,
    pub idr: bool,
    pub irap: bool,
    pub short_term_ref_pic_set_sps_flag: bool,
    pub num_delta_pocs_of_ref_rps_idx: u8,
    pub num_bits_for_st_ref_pic_set_in_slice: u16,
    pub reset_before_decode: bool,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub bitstream_payload_bytes: u64,
    pub bitstream_ring_allocation_index: u64,
    pub bitstream_ring_wrap_count: u32,
    pub bitstream_upload_elapsed_us: u64,
    pub fence_wait_elapsed_us: u64,
    pub dst_base_array_layer: u32,
    pub setup_slot_index: i32,
    pub decode_reference_slot_count: u32,
    pub decode_elapsed_us: u64,
    pub descriptor_update_elapsed_us: u64,
    pub acquire_elapsed_us: u64,
    pub record_elapsed_us: u64,
    pub submit_elapsed_us: u64,
    pub queue_present_elapsed_us: u64,
    pub present_elapsed_us: u64,
    pub present_result_since_start_us: u64,
}

impl NativeVulkanDirectPresentTimedFrame for NativeVulkanDirectH265ReadyPrefixFrameSnapshot {
    fn apply_direct_present_timing(&mut self, timing: NativeVulkanDirectPresentTiming) {
        self.acquire_elapsed_us = timing.acquire_elapsed_us;
        self.record_elapsed_us = timing.record_elapsed_us;
        self.submit_elapsed_us = timing.queue_submit_elapsed_us;
        self.queue_present_elapsed_us = timing.queue_present_elapsed_us;
        self.present_elapsed_us = timing.present_elapsed_us;
        self.present_result_since_start_us = timing.present_result_since_start_us;
    }
}
