use std::path::PathBuf;

use serde::Serialize;

use crate::core::FitMode;

use super::demux::NativeVulkanStreamingPacketQueueRuntimeSnapshot;
use super::direct_runtime::{
    NativeVulkanDirectOptionalPresentTimedFrame, NativeVulkanDirectOptionalPresentTiming,
};
use super::{
    NativeVulkanAudioClockRuntimeSnapshot, NativeVulkanAv1SequenceHeaderSnapshot,
    NativeVulkanAv1TemporalUnitSnapshot, NativeVulkanVideoSessionCodec,
};

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct NativeVulkanDirectAv1ReadyPrefixRuntimeSnapshot {
    pub runtime_elapsed_ms: u64,
    pub requested_codec: NativeVulkanVideoSessionCodec,
    pub picture_format: &'static str,
    pub requested_frame_count: u32,
    pub ready_prefix_frame_count: u32,
    pub requested_playback_frame_count: u32,
    pub processed_temporal_unit_count: u32,
    pub decoded_frame_count: u32,
    pub hidden_decoded_frame_count: u32,
    pub total_decoded_frame_count: u32,
    pub displayed_handoff_frame_count: u32,
    pub presented_frame_count: u32,
    pub decoded_frame_zero_copy_scope: &'static str,
    pub decoded_frame_zero_copy_status: &'static str,
    pub playback_loop_count: u32,
    pub loop_boundary_reset_count: u32,
    pub frame_sleep_count: u32,
    pub missed_frame_pacing_count: u32,
    pub total_frame_sleep_us: u64,
    pub max_frame_pacing_late_us: u64,
    pub average_present_fps: f64,
    pub average_present_result_fps: f64,
    pub average_present_result_drop_first_fps: f64,
    pub average_present_result_drop_first_60_fps: f64,
    pub present_result_first_interval_us: u64,
    pub present_result_max_interval_us: u64,
    pub present_result_max_interval_after_warmup_us: u64,
    pub present_result_over_budget_count: u32,
    pub present_result_over_budget_after_warmup_count: u32,
    pub present_result_missed_vblank_threshold_us: u64,
    pub present_result_missed_vblank_count: u32,
    pub present_result_missed_vblank_after_warmup_count: u32,
    pub configured: bool,
    pub source: PathBuf,
    pub source_extent: (u32, u32),
    pub fit: FitMode,
    pub target_max_fps: Option<u32>,
    pub wayland_surface_logical_size: (u32, u32),
    pub wayland_surface_buffer_size: (u32, u32),
    pub selected_physical_device_name: String,
    pub selected_physical_device_type: &'static str,
    pub present_queue_family_index: u32,
    pub present_queue_flags: Vec<&'static str>,
    pub video_decode_queue_family_index: u32,
    pub video_decode_queue_flags: Vec<&'static str>,
    pub video_decode_queue_codec_operations: Vec<String>,
    pub cross_queue_sync_strategy: &'static str,
    pub driver_max_dpb_slots: u32,
    pub av1_order_hint_offset_enabled: bool,
    pub av1_initial_sequence_header: NativeVulkanAv1SequenceHeaderSnapshot,
    pub av1_active_sequence_header: NativeVulkanAv1SequenceHeaderSnapshot,
    pub av1_active_sequence_header_source: &'static str,
    pub av1_active_sequence_header_changed_after_bootstrap: bool,
    pub av1_bootstrap_alignment_iterations: u32,
    pub stream_dpb_slots: u32,
    pub stream_max_active_reference_pictures: u32,
    pub session_max_dpb_slots: u32,
    pub session_max_active_reference_pictures: u32,
    pub swapchain_extent: (u32, u32),
    pub swapchain_image_count: usize,
    pub swapchain_format: String,
    pub present_mode: &'static str,
    pub pacing_strategy: &'static str,
    pub video_resource_memory_bytes: u64,
    pub session_memory_bytes: u64,
    pub bitstream_buffer_bytes: u64,
    pub bitstream_buffer_strategy: &'static str,
    pub bitstream_buffer_slot_count: u32,
    pub bitstream_buffer_slot_bytes: u64,
    pub bitstream_ring_capacity_bytes: u64,
    pub bitstream_ring_min_offset_alignment: u64,
    pub bitstream_ring_min_size_alignment: u64,
    pub bitstream_ring_wrap_count: u32,
    pub bitstream_ring_allocation_count: u64,
    pub bitstream_window_payload_bytes: u64,
    pub bitstream_upload_count: u32,
    pub bitstream_uploaded_bytes: u64,
    pub av1_demux_queue: NativeVulkanStreamingPacketQueueRuntimeSnapshot,
    pub av1_packet_queue_capacity: u32,
    pub av1_packet_queue_pulled_count: u32,
    pub av1_packet_queue_eos_count: u32,
    pub av1_packet_queue_loop_count: u32,
    pub av1_packet_queue_loop_skip_temporal_units: u32,
    pub av1_packet_queue_loop_skipped_temporal_units: u32,
    pub av1_packet_queue_bootstrap_discarded_temporal_units: u32,
    pub av1_packet_queue_max_payload_bytes: u64,
    pub av1_packet_queue_retained_payload_bytes: u64,
    pub av1_display_handoff_strategy: &'static str,
    pub av1_display_ring_slot_count: u32,
    pub av1_display_ring_memory_bytes: u64,
    pub av1_display_copy_count: u32,
    pub av1_display_copy_elided_count: u32,
    pub av1_present_command_buffer_strategy: &'static str,
    pub av1_present_queue_count: u32,
    pub av1_async_present_depth: u32,
    pub av1_present_frame_queue_depth: u32,
    pub av1_present_frame_preroll_count: u32,
    pub av1_present_frame_queue_submit_count: u32,
    pub av1_present_frame_queue_acquire_elapsed_us: u64,
    pub av1_present_frame_queue_acquire_max_us: u64,
    pub av1_present_frame_queue_record_elapsed_us: u64,
    pub av1_present_frame_queue_record_max_us: u64,
    pub av1_present_result_wait_count: u32,
    pub av1_present_result_wait_elapsed_us: u64,
    pub av1_present_result_wait_max_us: u64,
    pub av1_frame_context_selection_strategy: &'static str,
    pub av1_frame_context_ready_probe_count: u32,
    pub av1_frame_context_ready_hit_count: u32,
    pub av1_frame_context_fallback_count: u32,
    pub av1_frame_context_fence_wait_count: u32,
    pub av1_frame_context_fence_wait_elapsed_us: u64,
    pub av1_frame_context_fence_wait_max_us: u64,
    pub av1_display_ring_slot_wait_count: u32,
    pub av1_display_ring_slot_wait_elapsed_us: u64,
    pub av1_display_ring_slot_wait_max_us: u64,
    pub av1_display_ring_slot_reuse_sync_strategy: &'static str,
    pub av1_display_ring_slot_gpu_wait_count: u32,
    pub av1_display_ring_slot_gpu_signal_count: u32,
    pub av1_display_ring_slot_selection_strategy: &'static str,
    pub av1_display_ring_ready_probe_count: u32,
    pub av1_display_ring_ready_hit_count: u32,
    pub av1_display_ring_ready_fallback_count: u32,
    pub av1_swapchain_image_wait_count: u32,
    pub av1_swapchain_image_wait_elapsed_us: u64,
    pub av1_swapchain_image_wait_max_us: u64,
    pub av1_acquire_not_ready_count: u32,
    pub av1_acquire_wait_present_result_count: u32,
    pub av1_acquire_wait_present_result_elapsed_us: u64,
    pub av1_acquire_wait_present_result_max_us: u64,
    pub av1_acquired_image_queue_slot_count: u32,
    pub av1_acquired_image_queue_target_depth: u32,
    pub av1_acquired_image_queue_attempt_count: u32,
    pub av1_acquired_image_queue_hit_count: u32,
    pub av1_acquired_image_queue_miss_count: u32,
    pub av1_acquired_image_queue_wait_count: u32,
    pub av1_acquired_image_queue_wait_elapsed_us: u64,
    pub av1_acquired_image_queue_wait_max_us: u64,
    pub av1_acquired_image_queue_acquire_elapsed_us: u64,
    pub av1_acquired_image_queue_acquire_max_us: u64,
    pub av1_preacquire_target_depth: u32,
    pub av1_preacquire_grace_wait_us: u64,
    pub av1_preacquire_attempt_count: u32,
    pub av1_preacquire_hit_count: u32,
    pub av1_preacquire_not_ready_count: u32,
    pub av1_preacquire_elapsed_us: u64,
    pub av1_preacquire_max_us: u64,
    pub av1_hidden_decode_sync_strategy: &'static str,
    pub av1_hidden_decode_handoff_slot_count: u32,
    pub av1_hidden_decode_async_handoff_count: u32,
    pub av1_hidden_decode_handoff_unavailable_count: u32,
    pub av1_hidden_decode_fence_wait_count: u32,
    pub av1_hidden_decode_fence_wait_elapsed_us: u64,
    pub av1_hidden_decode_fence_wait_max_us: u64,
    pub av1_hidden_decode_process_elapsed_us: u64,
    pub av1_hidden_decode_process_max_us: u64,
    pub av1_hidden_decode_before_display_gap_count: u32,
    pub av1_hidden_decode_before_display_elapsed_us: u64,
    pub av1_hidden_decode_before_display_max_count: u32,
    pub av1_hidden_decode_before_display_max_elapsed_us: u64,
    pub av1_hidden_lookahead_decode_count: u32,
    pub av1_hidden_lookahead_stop_present_count: u32,
    pub av1_hidden_lookahead_stop_output_hazard_count: u32,
    pub av1_hidden_lookahead_stop_unready_count: u32,
    pub av1_visible_decode_ahead_strategy: &'static str,
    pub av1_visible_decode_ahead_attempt_count: u32,
    pub av1_visible_decode_ahead_ready_count: u32,
    pub av1_visible_decode_ahead_submit_count: u32,
    pub av1_visible_decode_ahead_skip_show_existing_count: u32,
    pub av1_visible_decode_ahead_skip_unready_count: u32,
    pub av1_visible_decode_ahead_skip_output_hazard_count: u32,
    pub av1_visible_decode_ahead_skip_bitstream_overlap_count: u32,
    pub av1_visible_decode_ahead_skip_display_slot_hazard_count: u32,
    pub av1_show_existing_display_cache_strategy: &'static str,
    pub av1_show_existing_display_cache_lookup_count: u32,
    pub av1_show_existing_display_cache_hit_count: u32,
    pub av1_show_existing_display_cache_miss_count: u32,
    pub av1_show_existing_display_cache_busy_count: u32,
    pub av1_show_existing_display_cache_stale_count: u32,
    pub av1_show_existing_display_cache_update_count: u32,
    pub av1_show_existing_display_cache_invalidate_count: u32,
    pub av1_show_existing_precopy_strategy: &'static str,
    pub av1_show_existing_precopy_attempt_count: u32,
    pub av1_show_existing_precopy_submit_count: u32,
    pub av1_show_existing_precopy_hit_count: u32,
    pub av1_show_existing_precopy_miss_count: u32,
    pub av1_show_existing_precopy_skip_no_handoff_count: u32,
    pub av1_show_existing_precopy_skip_source_layout_count: u32,
    pub av1_show_existing_precopy_skip_display_slot_busy_count: u32,
    pub av1_show_existing_precopy_stale_count: u32,
    pub av1_show_existing_precopy_invalidate_count: u32,
    pub av1_show_existing_direct_dpb_count: u32,
    pub av1_displayed_direct_dpb_count: u32,
    pub av1_hidden_decode_queue_wait_count: u32,
    pub av1_hidden_decode_queue_wait_elapsed_us: u64,
    pub av1_frame_context_count: u32,
    pub av1_decode_command_ring_depth: u32,
    pub av1_decode_pending_max_count: u32,
    pub av1_decode_deferred_hidden_count: u32,
    pub av1_decode_slot_wait_count: u32,
    pub av1_decode_slot_wait_elapsed_us: u64,
    pub av1_decode_slot_wait_max_us: u64,
    pub av1_decode_hidden_slot_wait_count: u32,
    pub av1_decode_hidden_slot_wait_elapsed_us: u64,
    pub av1_decode_hidden_slot_wait_max_us: u64,
    pub av1_bootstrap_temporal_units: Vec<NativeVulkanAv1TemporalUnitSnapshot>,
    pub pts_delta_min_ms: Option<u64>,
    pub pts_delta_max_ms: Option<u64>,
    pub pts_delta_expected_min_ms: Option<u64>,
    pub pts_delta_expected_max_ms: Option<u64>,
    pub pts_delta_in_expected_range: Option<bool>,
    pub audio_clock_probe: Option<NativeVulkanAudioClockRuntimeSnapshot>,
    pub diagnostic_hidden_frames: Vec<NativeVulkanDirectAv1ReadyPrefixFrameSnapshot>,
    pub frames: Vec<NativeVulkanDirectAv1ReadyPrefixFrameSnapshot>,
    pub last_render_error: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct NativeVulkanDirectAv1ReadyPrefixFrameSnapshot {
    pub playback_frame_index: u32,
    pub playback_loop_index: u32,
    pub ready_prefix_frame_index: u32,
    pub loop_boundary_reset: bool,
    pub temporal_unit_index: u32,
    pub pts_ns: Option<u64>,
    pub pts_delta_ns: Option<u64>,
    pub pts_ms: Option<u64>,
    pub pts_delta_ms: Option<u64>,
    pub frame_type: u8,
    pub frame_type_label: &'static str,
    pub show_existing_frame: bool,
    pub frame_to_show_map_idx: Option<u8>,
    pub show_frame: bool,
    pub order_hint: Option<u8>,
    pub current_frame_id: Option<u32>,
    pub expected_frame_ids: Vec<u32>,
    pub primary_ref_frame: Option<u8>,
    pub refresh_frame_flags: u8,
    pub frame_header_obu_offset: Option<u64>,
    pub frame_header_payload_offset: Option<u64>,
    pub frame_header_offset_for_vulkan: Option<u32>,
    pub skip_mode_present: bool,
    pub skip_mode_frame: [u8; 2],
    pub allow_high_precision_mv: bool,
    pub is_motion_mode_switchable: bool,
    pub use_ref_frame_mvs: bool,
    pub allow_warped_motion: bool,
    pub frame_size_override_flag: bool,
    pub render_and_frame_size_different: Option<bool>,
    pub frame_width: Option<u32>,
    pub frame_height: Option<u32>,
    pub render_width: Option<u32>,
    pub render_height: Option<u32>,
    pub reduced_tx_set: bool,
    pub reference_select: bool,
    pub tx_mode_select: bool,
    pub quantization_base_q_idx: u8,
    pub quantization_delta_q: [i8; 5],
    pub loop_filter_level: [u8; 4],
    pub loop_filter_sharpness: u8,
    pub cdef_damping_minus_3: u8,
    pub cdef_bits: u8,
    pub loop_restoration_uses_lr: bool,
    pub loop_restoration_uses_chroma_lr: bool,
    pub global_motion_type: [u8; 8],
    pub ref_frame_sign_bias: u8,
    pub av1_order_hint_offset_enabled: bool,
    pub std_picture_order_hints: Vec<u8>,
    pub setup_saved_order_hints: Vec<u8>,
    pub setup_std_saved_order_hints: Vec<u8>,
    pub reference_order_hints: Vec<u8>,
    pub reference_saved_order_hints: Vec<Vec<u8>>,
    pub reference_std_saved_order_hints: Vec<Vec<u8>>,
    pub reference_ref_frame_sign_bias: Vec<u8>,
    pub reference_frame_types: Vec<u8>,
    pub reference_name_order_hints: Vec<u8>,
    pub reference_name_dpb_slot_indices: Vec<i32>,
    pub reference_name_decode_slot_indices: Vec<i32>,
    pub reference_name_ref_frame_indices: Vec<i32>,
    pub disable_frame_end_update_cdf: bool,
    pub segmentation_enabled: bool,
    pub segmentation_update_map: bool,
    pub segmentation_temporal_update: bool,
    pub segmentation_update_data: bool,
    pub segmentation_feature_enabled: [u8; 8],
    pub segmentation_feature_data: [[i16; 8]; 8],
    pub loop_filter_delta_enabled: bool,
    pub loop_filter_delta_update: bool,
    pub loop_filter_ref_deltas: [i8; 8],
    pub loop_filter_mode_deltas: [i8; 2],
    pub reset_before_decode: bool,
    pub src_buffer_offset: u64,
    pub src_buffer_range: u64,
    pub bitstream_payload_bytes: u64,
    pub bitstream_ring_allocation_index: u64,
    pub bitstream_ring_wrap_count: u32,
    pub bitstream_upload_elapsed_us: u64,
    pub fence_wait_elapsed_us: u64,
    pub dst_base_array_layer: Option<u32>,
    pub displayed_base_array_layer: u32,
    pub setup_slot_index: Option<i32>,
    pub begin_reference_slot_strategy: &'static str,
    pub begin_reference_slot_count: u32,
    pub begin_reference_slot_indices: Vec<i32>,
    pub decode_reference_slot_count: u32,
    pub decode_reference_slot_indices: Vec<i32>,
    pub decode_query_status_raw: Option<i32>,
    pub decode_query_status: Option<&'static str>,
    pub reference_name_slot_indices: Vec<i32>,
    pub tile_count: u32,
    pub tile_offsets: Vec<u32>,
    pub tile_sizes: Vec<u32>,
    pub decode_elapsed_us: u64,
    pub descriptor_update_elapsed_us: u64,
    pub acquire_elapsed_us: u64,
    pub record_elapsed_us: u64,
    pub submit_elapsed_us: u64,
    pub queue_present_elapsed_us: u64,
    pub present_elapsed_us: u64,
    pub present_start_since_start_us: u64,
    pub acquire_start_since_start_us: u64,
    pub acquire_end_since_start_us: u64,
    pub present_job_send_since_start_us: u64,
    pub present_submit_start_since_start_us: u64,
    pub queue_present_start_since_start_us: u64,
    pub present_result_since_start_us: u64,
    pub readback_y_hash: Option<u64>,
    pub readback_uv_hash: Option<u64>,
    pub readback_y_unique_values: Option<u32>,
    pub readback_uv_unique_values: Option<u32>,
    pub readback_elapsed_us: Option<u64>,
}

impl NativeVulkanDirectOptionalPresentTimedFrame for NativeVulkanDirectAv1ReadyPrefixFrameSnapshot {
    fn apply_direct_optional_present_timing(
        &mut self,
        timing: NativeVulkanDirectOptionalPresentTiming,
    ) {
        if let Some(acquire_elapsed_us) = timing.acquire_elapsed_us {
            self.acquire_elapsed_us = acquire_elapsed_us;
        }
        if let Some(acquire_start_since_start_us) = timing.acquire_start_since_start_us {
            self.acquire_start_since_start_us = acquire_start_since_start_us;
        }
        if let Some(acquire_end_since_start_us) = timing.acquire_end_since_start_us {
            self.acquire_end_since_start_us = acquire_end_since_start_us;
        }
        if let Some(record_elapsed_us) = timing.record_elapsed_us {
            self.record_elapsed_us = record_elapsed_us;
        }
        self.submit_elapsed_us = timing.queue_submit_elapsed_us;
        self.queue_present_elapsed_us = timing.queue_present_elapsed_us;
        self.present_elapsed_us = timing.present_elapsed_us;
        if let Some(present_submit_start_since_start_us) =
            timing.present_submit_start_since_start_us
        {
            self.present_submit_start_since_start_us = present_submit_start_since_start_us;
        }
        if let Some(queue_present_start_since_start_us) = timing.queue_present_start_since_start_us
        {
            self.queue_present_start_since_start_us = queue_present_start_since_start_us;
        }
        self.present_result_since_start_us = timing.present_result_since_start_us;
    }
}
