#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_NV12: u32 = 0x3231_564e;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_P010: u32 = 0x3031_3050;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_R8: u32 = 0x2020_3852;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_R16: u32 = 0x2036_3152;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_GR88: u32 = 0x3838_5247;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_GR1616: u32 = 0x3233_5247;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_MOD_LINEAR: u64 = 0;
#[cfg(any(feature = "native-vulkan-gst-video", test))]
pub(super) const DRM_FORMAT_MOD_INVALID: u64 = 0x00ff_ffff_ffff_ffff;
