[workspace]
members = [
    "apps/tensor-shell",
    "apps/tensor-files",
    "apps/tensor-wallpaper",
    "apps/tensorland",
    "crates/tensor-drm",
    "crates/tensor-event",
    "crates/tensor-host",
    "crates/tensor-present",
    "crates/tensor-protocol",
    "crates/tensor-runtime",
    "crates/tensor-util",
    "crates/tensor-kdl",
    "crates/tensor-kdl-macros",
    "crates/vulkan-renderer",
    "crates/vulkan-renderer-build",
    "crates/wayland-client-runtime",
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[profile.release]
codegen-units = 1
lto = "thin"
