//! In-memory document represented by the chunked scene binary.

use crate::engine::scene::abi::*;

#[derive(Debug, Clone, PartialEq)]
pub struct SceneBinaryDocument {
    pub feature_flags: u64,
    pub strings: Vec<String>,
    pub project: SceneProjectRecord,
    pub resources: Vec<SceneResourceRecord>,
    pub resource_payload: Vec<u8>,
    pub textures: Vec<SceneTextureRecord>,
    pub texture_mips: Vec<SceneTextureMipRecord>,
    pub texture_payload: Vec<u8>,
    pub objects: Vec<SceneObjectRecord>,
    pub object_effects: Vec<SceneObjectEffectRecord>,
    pub object_animation_layers: Vec<SceneObjectAnimationLayerRecord>,
    pub object_transform_tracks: Vec<SceneObjectTransformTrackRecord>,
    pub object_transform_channels: Vec<SceneObjectTransformChannelRecord>,
    pub object_transform_keyframes: Vec<SceneObjectTransformKeyframeRecord>,
    pub puppet_animation_clips: Vec<ScenePuppetAnimationClipRecord>,
    pub puppet_animation_tracks: Vec<ScenePuppetAnimationTrackRecord>,
    pub puppet_animation_transform_samples: Vec<ScenePuppetAnimationTransformSampleRecord>,
    pub puppet_animation_opacity_samples: Vec<f32>,
    pub materials: Vec<SceneMaterialRecord>,
    pub material_passes: Vec<SceneMaterialPassRecord>,
    pub material_textures: Vec<SceneMaterialTextureRecord>,
    pub material_constants: Vec<SceneMaterialConstantRecord>,
    pub meshes: Vec<SceneMeshRecord>,
    pub mesh_vertices: Vec<SceneMeshVertexRecord>,
    pub mesh_indices: Vec<u32>,
    pub mesh_source_records: Vec<SceneMeshSourceRecord>,
    pub mesh_clipping_subdraws: Vec<SceneMeshClippingSubdrawRecord>,
    pub mesh_clipping_source_ordinals: Vec<u32>,
    pub mesh_clipping_slices: Vec<SceneMeshClippingSliceRecord>,
    pub puppets: Vec<ScenePuppetRecord>,
    pub puppet_bones: Vec<ScenePuppetBoneRecord>,
    pub puppet_attachments: Vec<ScenePuppetAttachmentRecord>,
    pub particles: Vec<SceneParticleSystemRecord>,
    pub effects: Vec<SceneEffectRecord>,
    pub effect_passes: Vec<SceneEffectPassRecord>,
    pub effect_bindings: Vec<SceneEffectBindingRecord>,
    pub effect_combos: Vec<SceneEffectComboRecord>,
    pub effect_fbos: Vec<SceneEffectFboRecord>,
    pub render_graphs: Vec<SceneRenderGraphRecord>,
    pub render_passes: Vec<SceneRenderPassRecord>,
    pub render_bindings: Vec<SceneRenderBindingRecord>,
    pub unsupported: Vec<SceneUnsupportedRecord>,
    pub image_targets: Vec<SceneImageTargetRecord>,
    pub shader_contracts: Vec<SceneShaderContractRecord>,
    pub shader_constant_names: Vec<SceneStringId>,
    pub script_programs: Vec<SceneScriptProgramRecord>,
    pub camera_parallax: SceneCameraParallaxRecord,
    pub object_parallax_depths: Vec<SceneObjectParallaxDepthRecord>,
}

impl Default for SceneBinaryDocument {
    fn default() -> Self {
        Self {
            feature_flags: SCENE_DEFAULT_FEATURE_FLAGS,
            strings: Vec::new(),
            project: empty_project_record(),
            resources: Vec::new(),
            resource_payload: Vec::new(),
            textures: Vec::new(),
            texture_mips: Vec::new(),
            texture_payload: Vec::new(),
            objects: Vec::new(),
            object_effects: Vec::new(),
            object_animation_layers: Vec::new(),
            object_transform_tracks: Vec::new(),
            object_transform_channels: Vec::new(),
            object_transform_keyframes: Vec::new(),
            puppet_animation_clips: Vec::new(),
            puppet_animation_tracks: Vec::new(),
            puppet_animation_transform_samples: Vec::new(),
            puppet_animation_opacity_samples: Vec::new(),
            materials: Vec::new(),
            material_passes: Vec::new(),
            material_textures: Vec::new(),
            material_constants: Vec::new(),
            meshes: Vec::new(),
            mesh_vertices: Vec::new(),
            mesh_indices: Vec::new(),
            mesh_source_records: Vec::new(),
            mesh_clipping_subdraws: Vec::new(),
            mesh_clipping_source_ordinals: Vec::new(),
            mesh_clipping_slices: Vec::new(),
            puppets: Vec::new(),
            puppet_bones: Vec::new(),
            puppet_attachments: Vec::new(),
            particles: Vec::new(),
            effects: Vec::new(),
            effect_passes: Vec::new(),
            effect_bindings: Vec::new(),
            effect_combos: Vec::new(),
            effect_fbos: Vec::new(),
            render_graphs: Vec::new(),
            render_passes: Vec::new(),
            render_bindings: Vec::new(),
            unsupported: Vec::new(),
            image_targets: Vec::new(),
            shader_contracts: Vec::new(),
            shader_constant_names: Vec::new(),
            script_programs: Vec::new(),
            camera_parallax: SceneCameraParallaxRecord::default(),
            object_parallax_depths: Vec::new(),
        }
    }
}

pub(super) fn empty_project_record() -> SceneProjectRecord {
    SceneProjectRecord {
        title: SceneStringId::NONE,
        wallpaper_type: SceneStringId::NONE,
        scene_file: SceneStringId::NONE,
        preview: SceneStringId::NONE,
        properties_json: SceneStringId::NONE,
        logical_width: 0,
        logical_height: 0,
        clear_color: [0.0, 0.0, 0.0, 1.0],
        ambient_color: [0.0, 0.0, 0.0, 1.0],
        skylight_color: [0.0, 0.0, 0.0, 1.0],
        camera_eye: SceneVec3::default(),
        camera_center: SceneVec3 {
            x: 0.0,
            y: 0.0,
            z: -1.0,
        },
        camera_up: SceneVec3 {
            x: 0.0,
            y: 1.0,
            z: 0.0,
        },
    }
}
