Ok(NativeVulkanVulkanaliaScenePresentSnapshot {
    binding: "vulkanalia",
    route: "scene-mesh-dynamic-rendering-present",
    loader: vulkan.loader_name.to_owned(),
    requested_api_version: ROADMAP_2026_API_VERSION.to_string(),
    runtime_elapsed_ms: elapsed.as_millis().min(u64::MAX as u128) as u64,
    frames_presented,
    average_present_fps: if elapsed.is_zero() {
        0.0
    } else {
        frames_presented as f64 / elapsed.as_secs_f64()
    },
    present_delta_min_micros,
    present_delta_max_micros,
    present_delta_over_6250us_count,
    present_delta_over_8334us_count,
    clear_color: options.clear_color,
    selected_queue: NativeVulkanVulkanaliaPresentQueueSnapshot {
        physical_device_index: selection.physical_device_index,
        physical_device_name: selection.physical_device_name,
        physical_device_type: selection.physical_device_type,
        queue_family_index: selection.queue_family_index,
        queue_count: selection.queue_count,
        queue_flags: queue_flag_labels(selection.queue_flags),
        supports_graphics: selection.queue_flags.contains(vk::QueueFlags::GRAPHICS),
        supports_present: true,
        supports_wayland_presentation: selection.supports_wayland_presentation,
    },
    device_extensions: present_device.extension_snapshot,
    swapchain: NativeVulkanVulkanaliaSwapchainSnapshot {
        created: true,
        format: format!("{:?}", swapchain_plan.format.format),
        color_space: format!("{:?}", swapchain_plan.format.color_space),
        present_mode: present_mode_label(swapchain_plan.present_mode),
        extent: (swapchain_plan.extent.width, swapchain_plan.extent.height),
        extent_selection: swapchain_plan.extent_selection,
        image_count: swapchain_images.len(),
        min_image_count: swapchain_plan.image_count,
        composite_alpha: composite_alpha_label(swapchain_plan.composite_alpha),
        image_usage: vec![
            "transfer-src",
            "transfer-dst",
            "color-attachment",
            "sampled",
        ],
        create_flags: swapchain_create_flag_labels(swapchain_plan.create_flags),
        present_id2_enabled: swapchain_plan.present_id2_enabled,
        present_wait2_enabled: swapchain_plan.present_wait2_enabled,
    },
    command_submit_model: "acquire_next_image_khr -> cmd_begin_rendering -> scene mesh draw -> queue_submit2 -> queue_present_khr",
    uses_synchronization2: true,
    uses_submit2: true,
    uses_dynamic_rendering: true,
    scene_color_rasterization_samples: if scene_color_msaa_enabled { "4x" } else { "1x" },
    uses_multisampled_render_to_single_sampled: multisampled_render_to_single_sampled_enabled,
    uses_explicit_scene_color_msaa_resolve: scene_color_msaa_enabled
        && !multisampled_render_to_single_sampled_enabled,
    scene_color_msaa_memory_bytes,
    frame_slot_count,
    effect_target_physical_image_count,
    effect_target_memory_bytes,
    effect_target_dynamic_rendering_recorded,
    effect_target_dynamic_rendering_pass_count,
    effect_batch_count,
    effect_batch_instance_count,
    effect_batch_field_count,
    effect_target_copy_command_count,
    effect_target_swap_reference_count,
    effect_target_mesh_draw_count,
    effect_target_discard_load_count,
    scene_color_mesh_draw_count,
    scene_color_recorded_mesh_draw_count,
    scene_color_attachment_clear_draw_count,
    scene_color_attachment_clear_frame_count,
    descriptor_model: "VK_EXT_descriptor_heap",
    descriptor_heap_resource_count,
    descriptor_heap_sampler_count,
    vertex_buffer_bytes,
    index_buffer_bytes,
    transform_uniform_bytes,
    material_uniform_bytes,
    audio_spectrum_model: audio_summary.model,
    audio_spectrum_ready: audio_summary.ready,
    audio_spectrum_peak: audio_summary.peak,
    audio_spectrum_active_band_count: audio_summary.active_band_count,
    skinning_storage_bytes,
    resource_residency,
    scene_texture_image_count,
    scene_texture_memory_bytes,
    released_resource_payload_bytes,
    released_texture_payload_bytes,
    released_mesh_vertex_payload_bytes,
    released_mesh_index_payload_bytes,
    sampled_fallback_texture_count,
    sampled_fallback_descriptor_count,
    sampled_scene_texture_descriptor_count,
    sampled_scene_color_snapshot_descriptor_count,
    sampled_effect_target_descriptor_count,
    effect_target_reference_cycle_length,
    transform_uniform_update_count,
    effect_uniform_update_count,
    skinning_storage_update_count,
    frame_state_update_total_micros,
    semantic_incremental_resolve_enabled: semantic_resolver.incremental_enabled(),
    semantic_retained_puppet_resolve_enabled: semantic_resolver.retained_puppet_enabled(),
    semantic_dynamic_entity_count: semantic_resolver.dynamic_entity_count(),
    scene_script_memory: semantic_resolver.script_memory_snapshot(),
    script_effect_visibility,
    semantic_resolve_total_micros,
    graph_update_total_micros,
    transform_update_total_micros,
    material_update_total_micros,
    skinning_update_total_micros,
    draw_policy_update_total_micros,
    sampled_descriptor_update_count,
    sampled_descriptor_update_total_micros,
    command_recording_total_micros,
    fence_wait_total_micros,
    acquire_wait_total_micros,
    queue_present_total_micros,
    gpu_timing: gpu_timing_snapshot,
    composite_scissor_draw_count,
    composite_scissor_covered_pixels,
    composite_scissor_avoided_pixels,
    scene_pipeline_count,
    mesh_draw_count,
    particle_instance_capacity,
    particle_gpu_emitter_count,
    particle_gpu_total_capacity,
    particle_gpu_state_bytes,
    particle_gpu_indirect_bytes,
    particle_gpu_frame_time_bytes,
    particle_gpu_device_local,
    particle_compute_pipeline_created,
    particle_compute_dispatch_enabled: particle_compute_pipeline_created,
    mesh_draw_recorded,
    command_order,
    present_backend: "vulkanalia-scene-present-runtime",
})
