//! Binary `.gscn` container and record constants.
//!
//! References:
//! - `reverse-engineered/docs/scene-format.md`
//! - `reverse-engineered/docs/project-format.md`

pub const SCENE_BINARY_MAGIC: [u8; 4] = *b"GSCN";
pub const SCENE_BINARY_VERSION_V12: u16 = 12;
pub const SCENE_BINARY_VERSION: u16 = 19;
pub const SCENE_BINARY_ENDIAN_LITTLE: u8 = 1;
pub const SCENE_BINARY_ALIGNMENT: u8 = 8;
pub const SCENE_BINARY_HEADER_SIZE: usize = 24;
pub const SCENE_BINARY_CHUNK_DESCRIPTOR_SIZE: usize = 24;
pub const SCENE_BINARY_TRANSFORM_TIMELINE_RECORD_SIZE: usize = 80;
pub const SCENE_BINARY_TRANSFORM_KEYFRAME_RECORD_SIZE: usize = 16;
pub const SCENE_BINARY_TEXTURE_SLOT_RECORD_SIZE: usize = 32;
pub const SCENE_BINARY_MATERIAL_PASS_RECORD_SIZE: usize = 58;
pub const SCENE_BINARY_EFFECT_PASS_RECORD_SIZE_V12: usize = 56;
pub const SCENE_BINARY_EFFECT_PASS_RECORD_SIZE: usize = 70;
pub const SCENE_BINARY_EFFECT_PARAMETER_RECORD_SIZE: usize = 48;
pub const SCENE_BINARY_RENDER_STATE_RECORD_SIZE: usize = 32;
pub const SCENE_BINARY_RETAINED_GPU_STATE_RECORD_SIZE: usize = 24;
pub const SCENE_BINARY_DEBUG_NAME_RECORD_SIZE: usize = 16;

pub const SCENE_BINARY_NONE_ID: u32 = u32::MAX;
pub(in crate::core::scene::binary) const SCENE_BINARY_DEFAULT_TRANSFORM_PROPERTY: u16 = 0;
pub const SCENE_BINARY_RETAINED_RESOURCE: u16 = 1;
pub const SCENE_BINARY_RETAINED_TEXTURE_SLOT: u16 = 2;
pub const SCENE_BINARY_RETAINED_MATERIAL_PASS: u16 = 3;
pub const SCENE_BINARY_RETAINED_EFFECT_PASS: u16 = 4;
pub const SCENE_BINARY_RETAINED_EFFECT_PARAMETER: u16 = 5;
pub const SCENE_BINARY_RETAINED_GEOMETRY: u16 = 6;
pub const SCENE_BINARY_RETAINED_EFFECT_UV_TRANSFORM: u16 = 7;
pub const SCENE_BINARY_RETAINED_PUPPET: u16 = 8;
pub const SCENE_BINARY_RETAINED_PARTICLE_EMITTER: u16 = 9;

pub const SCENE_BINARY_PARAMETER_VALUE_BOOL: u16 = 1;
pub const SCENE_BINARY_PARAMETER_VALUE_FLOAT: u16 = 2;
pub const SCENE_BINARY_PARAMETER_VALUE_INTEGER: u16 = 3;
pub const SCENE_BINARY_PARAMETER_VALUE_STRING: u16 = 4;
pub const SCENE_BINARY_PARAMETER_VALUE_VEC2: u16 = 5;
pub const SCENE_BINARY_PARAMETER_VALUE_VEC3: u16 = 6;
pub const SCENE_BINARY_PARAMETER_VALUE_VEC4: u16 = 7;

pub const SCENE_BINARY_PARAMETER_ROLE_EFFECT_PROPERTY: u16 = 1;
pub const SCENE_BINARY_PARAMETER_ROLE_PASS_CONSTANT: u16 = 2;
pub const SCENE_BINARY_PARAMETER_ROLE_PASS_COMBO: u16 = 4;
pub const SCENE_BINARY_PARAMETER_ROLE_PASS_BIND: u16 = 8;
pub const SCENE_BINARY_PARAMETER_ROLE_EFFECT_FBO: u16 = 16;

pub(in crate::core::scene::binary) const SCENE_BINARY_TEXTURE_ROLE_BASE_COLOR: u16 = 1;
pub(in crate::core::scene::binary) const SCENE_BINARY_TEXTURE_ROLE_EFFECT_INPUT: u16 = 2;
pub(in crate::core::scene::binary) const SCENE_BINARY_TEXTURE_ROLE_ALPHA_MASK: u16 = 4;
pub(in crate::core::scene::binary) const SCENE_BINARY_TEXTURE_ROLE_FIRST_CLASS_TARGET: u16 = 8;
